import 'emclass.dart';

void main(){

  List<Map<String,dynamic>> rawdata = <Map<String,dynamic>>[
    {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
        {
      'id' : 1,  
      'name' : "Rahul",
      'Designation' : "employee",
      'salary' : 8900,
      'Experience' : 5,
      'companyname' : "apple",
      'age' : 35,
      'Qualification' : "flutter",
      'gender' : "male",
      'moblino' : "9876543210",
    },
    
  ];
}